name: Update Gas Prices
on:
  schedule:
    - cron: '15 */12 * * *' # Run at 15 past the hour to avoid the "top of the hour" bot peak
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      
      - name: Wait for IP Clearance
        # Random sleep between 1 and 300 seconds
        run: sleep $((1 + $RANDOM % 300))
        
      - name: Run Fetcher
        run: python update_gas.py
        
      - name: Commit
        run: |
          git config --global user.name "GasBot"
          git config --global user.email "bot@github.com"
          git add gas_prices.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Sync" && git push)